# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('deposit_type', models.CharField(choices=[('client', 'Acompte client'), ('supplier', 'Avance fournisseur')], max_length=20, verbose_name='Type')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant original')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant appliqué')),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant restant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement appliqué'), ('applied', 'Appliqué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('purpose', models.CharField(blank=True, help_text='Ex: Acompte pour bague sur mesure', max_length=500, verbose_name='Objet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Acompte/Avance',
                'verbose_name_plural': 'Acomptes/Avances',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': "Application d'acompte",
                'verbose_name_plural': "Applications d'acomptes",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('party_type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Fournisseur')], max_length=20, verbose_name='Type')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant dû')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant restant')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement payé'), ('paid', 'Payé'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paiement en attente',
                'verbose_name_plural': 'Paiements en attente',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('payment_type', models.CharField(choices=[('invoice', 'Paiement facture'), ('advance', 'Avance'), ('consignment', 'Paiement consignation'), ('artisan', 'Paiement artisan')], default='invoice', max_length=20, verbose_name='Type de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique du paiement (numéro de chèque, virement, etc.)', max_length=100, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('payment_type', models.CharField(choices=[('invoice', 'Paiement facture'), ('deposit', 'Acompte'), ('layaway', 'Paiement mise de côté'), ('loan_deposit', 'Dépôt pour prêt'), ('advance', 'Avance'), ('refund', 'Remboursement')], default='invoice', max_length=20, verbose_name='Type de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('check_bank', models.CharField(blank=True, max_length=100, verbose_name='Banque du chèque')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='Date du chèque')),
                ('check_deposited', models.BooleanField(default=False, verbose_name='Chèque déposé')),
                ('check_deposit_date', models.DateField(blank=True, null=True, verbose_name='Date de dépôt')),
                ('check_cleared', models.BooleanField(default=False, verbose_name='Chèque encaissé')),
                ('check_bounce', models.BooleanField(default=False, verbose_name='Chèque impayé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Compte où le paiement a été reçu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.bankaccount', verbose_name='Compte bancaire')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': 'Paiements clients',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
