# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('payments', '0002_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('settings_app', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='layaway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.layaway', verbose_name='Mise de côté'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.paymentmethod', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.saleinvoice', verbose_name='Facture de vente'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.bankaccount', verbose_name='Compte bancaire'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.paymentmethod', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='depositapplication',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='depositapplication',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments.deposit', verbose_name='Acompte'),
        ),
        migrations.AddField(
            model_name='depositapplication',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_applications', to='purchases.purchaseinvoice', verbose_name="Facture d'achat"),
        ),
        migrations.AddField(
            model_name='depositapplication',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_applications', to='sales.saleinvoice', verbose_name='Facture de vente'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_payments', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='purchases.purchaseinvoice', verbose_name="Facture d'achat"),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='sales.saleinvoice', verbose_name='Facture de vente'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_payments', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='artisan_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.artisanjob', verbose_name='Travail artisan'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.consignment', verbose_name='Consignation'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='from_bank_account',
            field=models.ForeignKey(blank=True, help_text="Notre compte d'où part le paiement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_payments', to='settings_app.bankaccount', verbose_name='Depuis compte'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.paymentmethod', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.purchaseinvoice', verbose_name="Facture d'achat"),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='to_supplier_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='suppliers.supplierbankaccount', verbose_name='Vers compte fournisseur'),
        ),
    ]
