# Generated by Django 6.0.2 on 2026-02-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='Client'),
        ),
    ]
