# Generated by Django 6.0.2 on 2026-02-23 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0005_alter_printqueue_created_at_and_more'),
        ('sales', '0011_alter_delivery_delivery_method_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_storage_account', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_storage_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Compte Stock Client',
                'verbose_name_plural': 'Comptes Stock Client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(max_length=100, verbose_name='Réf. produit')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom produit')),
                ('product_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Poids (g)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('picked_up', 'Récupéré')], default='waiting', max_length=20, verbose_name='Statut')),
                ('stored_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de stockage')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de récupération')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock_storage.stockstorageaccount', verbose_name='Compte')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_storage_items', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_storage_items', to='sales.saleinvoice', verbose_name='Facture')),
                ('picked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_pickups', to=settings.AUTH_USER_MODEL, verbose_name='Récupéré par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_storage_items', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article en Stock Client',
                'verbose_name_plural': 'Articles en Stock Client',
                'ordering': ['-stored_at'],
                'indexes': [models.Index(fields=['status', '-stored_at'], name='stock_stora_status_39afbb_idx'), models.Index(fields=['account', 'status'], name='stock_stora_account_d2885d_idx')],
            },
        ),
    ]
