# Generated by Django 6.0.2 on 2026-02-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, help_text='Le compte Telegram a été vérifié et lié', verbose_name='Telegram vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID Telegram pour recevoir/envoyer des messages via le bot', max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username Telegram (sans @)', max_length=100, verbose_name="Nom d'utilisateur Telegram"),
        ),
    ]
