# Generated by Django 6.0.2 on 2026-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_telegram_verified_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gérant'), ('seller', 'Vendeur'), ('cashier', 'Caissier'), ('delivery', 'Responsable livraison')], default='seller', max_length=20, verbose_name='Rôle'),
        ),
    ]
