# Generated by Django 6.0.2 on 2026-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('description', models.TextField(verbose_name='Description du travail')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('weight_given', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Poids donné (g)')),
                ('stones_given', models.TextField(blank=True, help_text='Description des pierres fournies', verbose_name='Pierres données')),
                ('weight_returned', models.DecimalField(decimal_places=3, default=0, help_text='Poids total des pièces finies', max_digits=10, verbose_name='Poids retourné (g)')),
                ('pieces_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de pièces')),
                ('labor_cost_per_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Coût main d'œuvre par pièce")),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Coût total main d'œuvre")),
                ('date_sent', models.DateField(verbose_name="Date d'envoi")),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Travail artisan',
                'verbose_name_plural': 'Travaux artisans',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Nom (Arabe)')),
                ('supplier_type', models.CharField(choices=[('jewelry', 'Grossiste bijoux'), ('raw_material', 'Fournisseur matière première'), ('stones', 'Fournisseur pierres'), ('artisan', 'Artisan/Façonnier'), ('other', 'Autre')], default='jewelry', max_length=20, verbose_name='Type de fournisseur')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('ice', models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise", max_length=20, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, help_text='Registre de Commerce', max_length=20, verbose_name='RC')),
                ('specialty', models.CharField(blank=True, help_text='Ex: Bagues, Chaînes, Sertissage', max_length=200, verbose_name='Spécialité')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum de crédit autorisé', max_digits=12, verbose_name='Limite de crédit')),
                ('payment_terms', models.CharField(blank=True, help_text='Ex: 30 jours, Comptant', max_length=100, verbose_name='Conditions de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du titulaire')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte')),
                ('rib', models.CharField(blank=True, max_length=30, verbose_name='RIB')),
                ('is_default', models.BooleanField(default=False, verbose_name='Compte par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Compte bancaire fournisseur',
                'verbose_name_plural': 'Comptes bancaires fournisseurs',
            },
        ),
    ]
