# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='artisanjob',
            name='metal_purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings_app.metalpurity', verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='artisanjob',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings_app.metaltype', verbose_name='Type de métal'),
        ),
        migrations.AddField(
            model_name='artisanjob',
            name='artisan',
            field=models.ForeignKey(limit_choices_to={'supplier_type': 'artisan'}, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='suppliers.supplier', verbose_name='Artisan'),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
    ]
