# Generated by Django 6.0.2 on 2026-02-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0003_product_bank_account'),
        ('sales', '0008_add_return_exchange'),
        ('settings_app', '0003_systemconfig_alter_metaltype_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_account', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deposit_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Compte Dépôt',
                'verbose_name_plural': 'Comptes Dépôt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('purchase', 'Achat'), ('withdrawal', 'Retrait'), ('adjustment', 'Ajustement'), ('refund', 'Remboursement')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif pour dépôt, négatif pour achat/retrait', max_digits=12, verbose_name='Montant')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde après')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='deposits.depositaccount', verbose_name='Compte')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.bankaccount', verbose_name='Compte bancaire')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='sales.saleinvoice', verbose_name='Facture')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.paymentmethod', verbose_name='Mode de paiement')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_purchases', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Transaction Dépôt',
                'verbose_name_plural': 'Transactions Dépôt',
                'ordering': ['-created_at'],
            },
        ),
    ]
