# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_received', models.DateField(verbose_name='Date de réception')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('partial', 'Partiellement vendu'), ('sold', 'Tout vendu'), ('returned', 'Retourné'), ('closed', 'Clôturé')], default='active', max_length=20, verbose_name='Statut')),
                ('return_deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de retour')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage gardé sur les ventes', max_digits=5, verbose_name='Commission (%)')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total articles')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valeur totale')),
                ('items_sold', models.PositiveIntegerField(default=0, verbose_name='Articles vendus')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant dû au fournisseur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Consignation',
                'verbose_name_plural': 'Consignations',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='Prix à payer au fournisseur si vendu', max_digits=12, verbose_name='Prix convenu')),
                ('minimum_selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente minimum')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente effectif')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendu'), ('returned', 'Retourné')], default='available', max_length=20, verbose_name='Statut')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Date de vente')),
                ('date_returned', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Article en consignation',
                'verbose_name_plural': 'Articles en consignation',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('supplier_invoice_ref', models.CharField(blank=True, max_length=100, verbose_name='Référence facture fournisseur')),
                ('date', models.DateField(verbose_name='Date')),
                ('invoice_type', models.CharField(choices=[('finished', 'Bijoux finis'), ('raw_material', 'Matière première'), ('stones', 'Pierres'), ('labor', "Main d'œuvre seule"), ('mixed', 'Mixte')], default='finished', max_length=20, verbose_name='Type de facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmé'), ('partial', 'Partiellement payé'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde dû')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Facture d'achat",
                'verbose_name_plural': "Factures d'achat",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids brut (g)')),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids net (g)')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix par gramme')),
                ('metal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût métal')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Main d'œuvre")),
                ('stone_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût pierres')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres coûts')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Ligne de facture achat',
                'verbose_name_plural': 'Lignes de facture achat',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('order_type', models.CharField(choices=[('finished', 'Bijoux finis'), ('raw_material', 'Matière première'), ('stones', 'Pierres'), ('artisan', 'Travail artisan'), ('custom', 'Commande sur mesure client')], default='finished', max_length=20, verbose_name='Type de commande')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', "En attente d'approbation"), ('approved', 'Approuvé'), ('ordered', 'Commandé'), ('partial', 'Partiellement reçu'), ('received', 'Reçu'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('estimated_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Poids estimé (g)')),
                ('estimated_price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix estimé par gramme')),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Main d'œuvre estimée")),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Quantité reçue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
