# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name_ar', models.CharField(blank=True, max_length=100, verbose_name='Prénom (Arabe)')),
                ('last_name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('client_type', models.CharField(choices=[('regular', 'Particulier'), ('vip', 'VIP'), ('wholesale', 'Grossiste')], default='regular', max_length=20, verbose_name='Type de client')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('cin', models.CharField(blank=True, help_text="Carte d'Identité Nationale", max_length=20, verbose_name='CIN')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('wedding_anniversary', models.DateField(blank=True, null=True, verbose_name='Anniversaire de mariage')),
                ('preferences', models.TextField(blank=True, help_text='Ex: Préfère or 18K, style moderne', verbose_name='Préférences')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum de crédit autorisé', max_digits=12, verbose_name='Limite de crédit')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Points de fidélité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('preferred_metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.metaltype', verbose_name='Métal préféré')),
                ('preferred_purity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.metalpurity', verbose_name='Titre préféré')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OldGoldPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du vendeur')),
                ('client_cin', models.CharField(blank=True, max_length=20, verbose_name='CIN')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('tested_purity', models.DecimalField(decimal_places=2, help_text='Pureté réelle après test', max_digits=5, verbose_name='Pureté testée (%)')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Poids brut (g)')),
                ('net_weight', models.DecimalField(decimal_places=3, help_text='Poids après déduction (pierres, etc.)', max_digits=10, verbose_name='Poids net (g)')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par gramme')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence paiement')),
                ('destination', models.CharField(choices=[('stock', 'Stock matière première'), ('melting', 'Fonte'), ('resale', 'Revente'), ('refinery', 'Raffinerie')], default='stock', max_length=50, verbose_name='Destination')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_gold_sales', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Achat ancien or',
                'verbose_name_plural': 'Achats ancien or',
                'ordering': ['-date'],
            },
        ),
    ]
