# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oldgoldpurchase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='oldgoldpurchase',
            name='metal_purity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.metalpurity', verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='oldgoldpurchase',
            name='metal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.metaltype', verbose_name='Type de métal'),
        ),
        migrations.AddField(
            model_name='oldgoldpurchase',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.paymentmethod', verbose_name='Mode de paiement'),
        ),
    ]
