# Generated by Django 6.0.2 on 2026-02-05 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0007_invoicephoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=50, verbose_name='Chat ID')),
                ('status', models.CharField(choices=[('collecting', 'En cours de collecte'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='collecting', max_length=20, verbose_name='Statut')),
                ('photo_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de photos')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('last_message_id', models.CharField(blank=True, max_length=50, verbose_name='Dernier message ID')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_session', to='sales.saleinvoice', verbose_name='Facture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session photo Telegram',
                'verbose_name_plural': 'Sessions photo Telegram',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TempPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_file_id', models.CharField(max_length=255, verbose_name='Telegram File ID')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('caption', models.TextField(blank=True, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_photos', to='telegram_bot.pendingphotosession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Photo temporaire',
                'verbose_name_plural': 'Photos temporaires',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
