# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('account_name', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte')),
                ('rib', models.CharField(blank=True, help_text="Relevé d'Identité Bancaire", max_length=30, verbose_name='RIB')),
                ('swift', models.CharField(blank=True, max_length=20, verbose_name='Code SWIFT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Compte par défaut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Émetteur de certificat',
                'verbose_name_plural': 'Émetteurs de certificats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_name_ar', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise (Arabe)")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('ice', models.CharField(blank=True, help_text="Identifiant Commun de l'Entreprise", max_length=20, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, help_text='Registre de Commerce', max_length=20, verbose_name='RC')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('default_margin_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de marge par défaut')),
                ('default_margin_value', models.DecimalField(decimal_places=2, default=25, help_text='Pourcentage ou montant fixe selon le type', max_digits=10, verbose_name='Valeur de marge par défaut')),
                ('quote_validity_days', models.PositiveIntegerField(default=30, verbose_name='Validité des devis (jours)')),
                ('custom_order_deposit_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Acompte commande sur mesure (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_internal', models.BooleanField(default=False, help_text='Livreur de la boutique', verbose_name='Livraison interne')),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mode de livraison',
                'verbose_name_plural': 'Modes de livraison',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Type de métal',
                'verbose_name_plural': 'Types de métaux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('requires_reference', models.BooleanField(default=False, help_text='Ex: numéro de chèque, référence virement', verbose_name='Référence obligatoire')),
                ('requires_bank_account', models.BooleanField(default=False, verbose_name='Compte bancaire obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par défaut')),
                ('estimated_duration_days', models.PositiveIntegerField(default=1, verbose_name='Durée estimée (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Type de réparation',
                'verbose_name_plural': 'Types de réparations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_secure', models.BooleanField(default=False, help_text='Coffre-fort, etc.', verbose_name='Emplacement sécurisé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Emplacement de stock',
                'verbose_name_plural': 'Emplacements de stock',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoneClarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Plus le rang est bas, meilleure est la clarté', verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Clarté de pierre',
                'verbose_name_plural': 'Clartés de pierres',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Plus le rang est bas, meilleure est la couleur', verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Couleur de pierre',
                'verbose_name_plural': 'Couleurs de pierres',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StoneCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (Arabe)')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Taille de pierre',
                'verbose_name_plural': 'Tailles de pierres',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=50, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('is_precious', models.BooleanField(default=False, help_text='Diamant, Rubis, Saphir, Émeraude', verbose_name='Pierre précieuse')),
                ('requires_certificate', models.BooleanField(default=False, verbose_name='Certificat requis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Type de pierre',
                'verbose_name_plural': 'Types de pierres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings_app.productcategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('purity_percentage', models.DecimalField(decimal_places=2, help_text='Exemple: 75.00 pour 18K', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de pureté')),
                ('hallmark', models.CharField(blank=True, help_text='Poinçon officiel', max_length=20, verbose_name='Poinçon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purities', to='settings_app.metaltype', verbose_name='Type de métal')),
            ],
            options={
                'verbose_name': 'Titre/Pureté',
                'verbose_name_plural': 'Titres/Puretés',
                'ordering': ['metal_type', '-purity_percentage'],
                'unique_together': {('metal_type', 'name')},
            },
        ),
    ]
