# Generated by Django 6.0.2 on 2026-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Référence unique générée automatiquement', max_length=50, null=True, unique=True, verbose_name='Référence'),
        ),
    ]
