# Generated by Django 6.0.2 on 2026-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_bankaccount_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaltype',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stoneclarity',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stonecolor',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stonetype',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
    ]
