# Generated by Django 6.0.2 on 2026-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_bankaccount_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Token du bot Telegram pour les notifications', max_length=100, verbose_name='Token Bot Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID du chat/groupe pour recevoir les notifications', max_length=50, verbose_name='Chat ID Telegram')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram activé')),
                ('zebra_printer_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'imprimante Zebra", null=True, verbose_name='IP Imprimante Zebra')),
                ('zebra_printer_port', models.PositiveIntegerField(default=9100, help_text="Port de l'imprimante (défaut: 9100)", verbose_name='Port Imprimante Zebra')),
                ('zebra_printer_enabled', models.BooleanField(default=False, verbose_name='Imprimante Zebra activée')),
                ('zebra_label_width', models.PositiveIntegerField(default=50, help_text='Largeur des étiquettes en millimètres', verbose_name='Largeur étiquette (mm)')),
                ('zebra_label_height', models.PositiveIntegerField(default=25, help_text='Hauteur des étiquettes en millimètres', verbose_name='Hauteur étiquette (mm)')),
                ('server_base_url', models.URLField(blank=True, help_text='URL publique du serveur (ex: https://erp.bijouterie-hafsa.ma)', verbose_name='URL de base du serveur')),
                ('debug_mode', models.BooleanField(default=False, help_text='Activer le mode debug (désactiver en production)', verbose_name='Mode Debug')),
                ('smtp_host', models.CharField(blank=True, help_text="Serveur SMTP pour l'envoi d'emails", max_length=200, verbose_name='Serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='Port SMTP (défaut: 587 pour TLS)', verbose_name='Port SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=200, verbose_name='Utilisateur SMTP')),
                ('smtp_password', models.CharField(blank=True, help_text='Mot de passe ou App Password', max_length=200, verbose_name='Mot de passe SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('smtp_from_email', models.EmailField(blank=True, help_text="Adresse email pour l'envoi", max_length=254, verbose_name='Email expéditeur')),
                ('backup_enabled', models.BooleanField(default=False, verbose_name='Sauvegarde automatique')),
                ('backup_path', models.CharField(blank=True, help_text='Chemin du dossier de sauvegarde', max_length=500, verbose_name='Chemin de sauvegarde')),
                ('backup_retention_days', models.PositiveIntegerField(default=30, verbose_name='Rétention sauvegardes (jours)')),
                ('gold_price_api_key', models.CharField(blank=True, help_text="Clé API pour récupérer les prix de l'or", max_length=200, verbose_name="Clé API Prix de l'Or")),
                ('gold_price_api_url', models.URLField(blank=True, help_text="URL de l'API pour les prix de l'or", verbose_name="URL API Prix de l'Or")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configuration système',
            },
        ),
        migrations.AlterField(
            model_name='metaltype',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stoneclarity',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stonecolor',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stonetype',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Code'),
        ),
    ]
