# Generated by Django 6.0.2 on 2026-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_systemconfig_alter_metaltype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('tracking_url_template', models.URLField(blank=True, help_text='URL template avec {tracking_code} pour le numéro de suivi', verbose_name='URL de suivi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('supports_auto_tracking', models.BooleanField(default=False, help_text='Permet le suivi automatique via scraping (ex: AMANA)', verbose_name='Suivi automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
                'ordering': ['name'],
            },
        ),
    ]
