# Generated by Django 6.0.2 on 2026-02-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_systemconfig_alter_metaltype_code_and_more'),
        ('settings_app', '0004_add_delivery_tracking'),
    ]

    operations = [
    ]
