# Generated by Django 6.0.2 on 2026-02-03 23:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0002_initial'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne contact')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Spécifications')),
                ('subtotal_dh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sous-total (DH)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Remise (%)')),
                ('discount_amount_dh', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant de la remise (DH)')),
                ('tax_amount_dh', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant taxe (DH)')),
                ('total_amount_dh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant total (DH)')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('valid_until_date', models.DateField(verbose_name="Valide jusqu'au")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré'), ('converted', 'Converti en commande')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Conditions générales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client', verbose_name='Client')),
                ('converted_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='sales.saleinvoice', verbose_name='Commande convertie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price_dh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix unitaire (DH)')),
                ('line_total_dh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total (DH)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='products.product', verbose_name='Produit')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Article de devis',
                'verbose_name_plural': 'Articles de devis',
            },
        ),
    ]
