# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Retourné')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Vendu')),
            ],
            options={
                'verbose_name': 'Article prêté',
                'verbose_name_plural': 'Articles prêtés',
            },
        ),
        migrations.CreateModel(
            name='Layaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='active', max_length=20, verbose_name='Statut')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix convenu')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total payé')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde dû')),
                ('expiry_date', models.DateField(help_text='Date limite pour compléter le paiement', verbose_name="Date d'expiration")),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date de complétion')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Mise de côté',
                'verbose_name_plural': 'Mises de côté',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('sale_type', models.CharField(choices=[('regular', 'Vente normale'), ('credit', 'Vente à crédit'), ('layaway', 'Mise de côté (acompte)'), ('consignment', 'Vente consignation')], default='regular', max_length=20, verbose_name='Type de vente')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmé'), ('partial', 'Partiellement payé'), ('paid', 'Payé'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant remise')),
                ('old_gold_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant déduit pour ancien or repris', max_digits=12, verbose_name='Reprise ancien or')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde dû')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('delivery_status', models.CharField(choices=[('pending', 'En attente'), ('shipped', 'Expédié'), ('in_transit', 'En cours'), ('delivered', 'Livré')], default='pending', max_length=20, verbose_name='Statut livraison')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Facture de vente',
                'verbose_name_plural': 'Factures de vente',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Prix avant négociation', max_digits=12, verbose_name='Prix original')),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix négocié')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Ligne de facture vente',
                'verbose_name_plural': 'Lignes de facture vente',
            },
        ),
        migrations.CreateModel(
            name='ClientLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('returned', 'Retourné'), ('sold', 'Vendu'), ('overdue', 'En retard')], default='active', max_length=20, verbose_name='Statut')),
                ('return_date', models.DateField(verbose_name='Date de retour prévue')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Acompte laissé par le client', max_digits=12, verbose_name='Montant du dépôt')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Date de retour effectif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Prêt client',
                'verbose_name_plural': 'Prêts clients',
                'ordering': ['-date'],
            },
        ),
    ]
