# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='clientloanitem',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.clientloan', verbose_name='Prêt'),
        ),
        migrations.AddField(
            model_name='clientloanitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='products.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='layaway',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layaways', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='layaway',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='layaway',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layaways', to='products.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.deliverymethod', verbose_name='Mode de livraison'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.deliveryperson', verbose_name='Livreur'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Remise approuvée par'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='old_gold_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_to_sales', to='clients.oldgoldpurchase', verbose_name='Achat ancien or'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='layaway',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_layaway', to='sales.saleinvoice', verbose_name='Facture de vente'),
        ),
        migrations.AddField(
            model_name='clientloanitem',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_loan_items', to='sales.saleinvoice', verbose_name='Facture de vente'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleinvoice', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Produit'),
        ),
    ]
