# Generated by Django 6.0.2 on 2026-02-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invoice_photos/%Y/%m/%d/', verbose_name='Image')),
                ('photo_type', models.CharField(choices=[('product', 'Photo produit'), ('invoice', 'Facture manuscrite'), ('payment', 'Preuve de paiement'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de photo')),
                ('telegram_file_id', models.CharField(blank=True, help_text='ID du fichier Telegram pour référence', max_length=255, verbose_name='Telegram File ID')),
                ('caption', models.TextField(blank=True, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
            ],
            options={
                'verbose_name': 'Photo de facture',
                'verbose_name_plural': 'Photos de factures',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('unpaid', 'Non payée'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='unpaid', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='invoicephoto',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sales.saleinvoice', verbose_name='Facture'),
        ),
    ]
