# Generated by Django 6.0.2 on 2026-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_return_exchange'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saleinvoice',
            new_name='sales_salei_is_dele_9f08b3_idx',
            old_name='sales_saleinvoice_is_deleted_date_idx',
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='is_returned',
            field=models.BooleanField(default=False, help_text='Indique si cet article a été retourné', verbose_name='Retourné'),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retour'),
        ),
    ]
