# Generated by Django 6.0.2 on 2026-02-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_return_exchange'),
        ('settings_app', '0004_add_delivery_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nom client')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone client')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('delivery_method_type', models.CharField(choices=[('magasin', 'Magasin (Retrait)'), ('amana', 'AMANA'), ('transporteur', 'Autre Transporteur')], default='amana', max_length=20, verbose_name='Type de livraison')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Numéro de suivi')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('delivered', 'Livré')], default='pending', max_length=20, verbose_name='Statut')),
                ('product', models.CharField(blank=True, max_length=200, verbose_name='Produit AMANA')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Poids')),
                ('amount_cod', models.CharField(blank=True, max_length=50, verbose_name='Montant contre remboursement')),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='Position actuelle')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='Origine')),
                ('deposit_date', models.CharField(blank=True, max_length=50, verbose_name='Date de dépôt')),
                ('delivery_date', models.CharField(blank=True, max_length=50, verbose_name='Date de livraison')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(max_length=10, verbose_name='Numéro événement')),
                ('event_date', models.CharField(max_length=50, verbose_name='Date')),
                ('event_time', models.CharField(max_length=20, verbose_name='Heure')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('source', models.CharField(choices=[('amana', 'AMANA (automatique)'), ('manual', 'Manuel')], default='amana', max_length=20, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Événement livraison',
                'verbose_name_plural': 'Événements livraison',
                'ordering': ['-event_number'],
            },
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Transporteur externe (AMANA, autre)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.carrier', verbose_name='Transporteur'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_method_type',
            field=models.CharField(choices=[('magasin', 'Magasin (Retrait)'), ('amana', 'AMANA'), ('transporteur', 'Autre Transporteur')], default='magasin', max_length=20, verbose_name='Type de livraison'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Code de suivi pour AMANA ou autre transporteur', max_length=100, verbose_name='Numéro de suivi'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.deliverymethod', verbose_name='Mode de livraison (legacy)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.carrier', verbose_name='Transporteur'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.saleinvoice', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='deliverytimelineevent',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='sales.delivery', verbose_name='Livraison'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', '-created_at'], name='sales_deliv_status_20601b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tracking_number'], name='sales_deliv_trackin_77fa64_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytimelineevent',
            index=models.Index(fields=['delivery', '-event_number'], name='sales_deliv_deliver_6e75cc_idx'),
        ),
    ]
