# Generated by Django 6.0.2 on 2026-02-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_sales_saleinvoice_is_deleted_date_idx_sales_salei_is_dele_9f08b3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method_type',
            field=models.CharField(choices=[('magasin', 'Magasin (Retrait)'), ('amana', 'AMANA'), ('transporteur', 'Autre Transporteur'), ('en_stock', 'En Stock (Garde)')], default='amana', max_length=20, verbose_name='Type de livraison'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('to_pickup', 'À récupérer'), ('delivered', 'Livré'), ('returned', 'Retourné')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='delivery_method_type',
            field=models.CharField(choices=[('magasin', 'Magasin (Retrait)'), ('amana', 'AMANA'), ('transporteur', 'Autre Transporteur'), ('en_stock', 'En Stock (Garde)')], default='magasin', max_length=20, verbose_name='Type de livraison'),
        ),
    ]
