# Generated by Django 6.0.2 on 2026-03-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_delivery_delivery_method_type_and_more'),
        ('sales', '0011_unique_active_reference_only'),
    ]

    operations = [
    ]
