# Generated by Django 6.0.2 on 2026-09-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_amana_statement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Déposé chez AMANA le'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='deposited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposited_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retour réceptionné le'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_return_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Retour réceptionné par'),
        ),
    ]
