# Generated by Django 6.0.2 on 2026-09-05 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_delivery_deposited_at_delivery_deposited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_photos/%Y/%m/%d/', verbose_name='Photo')),
                ('photo_type', models.CharField(choices=[('code_change', 'Bordereau (code modifié)'), ('return_reception', 'Retour réceptionné')], default='code_change', max_length=20, verbose_name='Type')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sales.delivery', verbose_name='Livraison')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_photos', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Photo livraison',
                'verbose_name_plural': 'Photos livraison',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery', '-created_at'], name='sales_deliv_deliver_095ab8_idx')],
            },
        ),
    ]
