# Generated by Django 6.0.2 on 2026-09-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_delivery_return_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activé')),
                ('token', models.TextField(blank=True, verbose_name="Token d'accès")),
                ('phone_number_id', models.CharField(blank=True, max_length=64, verbose_name='Phone Number ID')),
                ('retour_group_id', models.CharField(blank=True, max_length=128, verbose_name='ID du groupe retour')),
                ('api_version', models.CharField(default='v25.0', max_length=16, verbose_name='Version API')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration WhatsApp',
                'verbose_name_plural': 'Configuration WhatsApp',
            },
        ),
    ]
