# Generated by Django 6.0.2 on 2026-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_dataexportjob_id_whatsappconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_verify_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='Verify token (webhook)'),
        ),
    ]
