# Generated by Django 6.0.2 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_whatsappconfig_webhook_verify_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='recipients',
            field=models.TextField(blank=True, help_text='Numéros WhatsApp, chiffres uniquement, séparés par des virgules', verbose_name='Destinataires (numéros)'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='template_lang',
            field=models.CharField(blank=True, default='fr', max_length=12, verbose_name='Langue du modèle'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='template_name',
            field=models.CharField(blank=True, default='retour_recu', max_length=128, verbose_name='Nom du modèle'),
        ),
    ]
