# Generated by Django 6.0.2 on 2026-09-26 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_whatsappconfig_recipients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='Motif de renvoi'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='submission',
            field=models.JSONField(blank=True, null=True, verbose_name='Saisie mobile'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sale_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
        migrations.AlterField(
            model_name='invoicephoto',
            name='photo_type',
            field=models.CharField(choices=[('product', 'Photo produit'), ('invoice', 'Facture manuscrite'), ('payment', 'Preuve de paiement'), ('delivery', 'Bordereau de livraison'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de photo'),
        ),
    ]
