# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('carat_weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids (carats)')),
                ('total_carat_weight', models.DecimalField(decimal_places=3, default=0, help_text='Calculé: quantité × poids unitaire', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids total (carats)')),
                ('shape', models.CharField(blank=True, help_text='Rond, Princesse, Ovale, etc.', max_length=50, verbose_name='Forme')),
                ('cost_per_carat', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût par carat')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût total')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Avec certificat')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certificat')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/stones/', verbose_name='Fichier certificat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Pierre du produit',
                'verbose_name_plural': 'Pierres du produit',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids actuel (g)')),
                ('minimum_weight', models.DecimalField(decimal_places=3, default=0, help_text='Alerte quand le stock est en dessous', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids minimum (g)')),
                ('average_cost_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût moyen par gramme')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Matière première',
                'verbose_name_plural': 'Matières premières',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('artisan_out', 'Envoi artisan'), ('artisan_in', 'Retour artisan'), ('old_gold_in', 'Achat ancien or'), ('adjustment', 'Ajustement'), ('loss', 'Perte')], max_length=20, verbose_name='Type de mouvement')),
                ('weight', models.DecimalField(decimal_places=3, help_text='Positif pour entrée, négatif pour sortie', max_digits=12, verbose_name='Poids (g)')),
                ('price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par gramme')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('reference', models.CharField(blank=True, help_text='Numéro de facture, bon, etc.', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Mouvement matière première',
                'verbose_name_plural': 'Mouvements matière première',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique du produit', max_length=50, unique=True, verbose_name='Référence')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('rfid_tag', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tag RFID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Nom (Arabe)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('product_type', models.CharField(choices=[('finished', 'Bijou fini'), ('raw_material', 'Matière première'), ('stone', 'Pierre'), ('component', 'Composant')], default='finished', max_length=20, verbose_name='Type de produit')),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids brut (g)')),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, help_text='Poids du métal sans les pierres', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Poids net (g)')),
                ('size', models.CharField(blank=True, help_text='Taille de bague, longueur de chaîne, etc.', max_length=20, verbose_name='Taille')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longueur (cm)')),
                ('purchase_price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat par gramme")),
                ('metal_cost', models.DecimalField(decimal_places=2, default=0, help_text='Calculé: poids net × prix/gramme', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût métal')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Main d'œuvre (façon)")),
                ('stone_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût des pierres')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Autres coûts')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text="Calculé: métal + main d'œuvre + pierres + autres", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût total')),
                ('margin_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20, verbose_name='Type de marge')),
                ('margin_value', models.DecimalField(decimal_places=2, default=25, max_digits=10, verbose_name='Valeur de marge')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente')),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix en dessous duquel la vente nécessite approbation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix minimum')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('sold', 'Vendu'), ('in_repair', 'En réparation'), ('consigned_in', 'En consignation (reçu)'), ('consigned_out', 'En consignation (prêté)'), ('returned', 'Retourné'), ('custom_order', 'Commande sur mesure')], default='available', max_length=20, verbose_name='Statut')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image principale')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Avec certificat')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certificat')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier certificat')),
                ('is_custom_order', models.BooleanField(default=False, verbose_name='Commande sur mesure')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='settings_app.productcategory', verbose_name='Catégorie')),
                ('certificate_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='settings_app.certificateissuer', verbose_name='Émetteur du certificat')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
