# Generated by Django 6.0.2 on 2026-02-03 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        ('settings_app', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_order_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_orders', to='clients.client', verbose_name='Client (commande sur mesure)'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='settings_app.stocklocation', verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='settings_app.metalpurity', verbose_name='Titre/Pureté'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='settings_app.metaltype', verbose_name='Type de métal'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='purchases.purchaseinvoice', verbose_name="Facture d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='certificate_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.certificateissuer', verbose_name='Émetteur du certificat'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='clarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stones', to='settings_app.stoneclarity', verbose_name='Clarté'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stones', to='settings_app.stonecolor', verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stones', to='settings_app.stonecut', verbose_name='Taille'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='products.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='productstone',
            name='stone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stones', to='settings_app.stonetype', verbose_name='Type de pierre'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.stocklocation', verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='metal_purity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='settings_app.metalpurity', verbose_name='Titre/Pureté'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='metal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='settings_app.metaltype', verbose_name='Type de métal'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='suppliers.supplier', verbose_name='Artisan'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.rawmaterial', verbose_name='Matière première'),
        ),
        migrations.AddField(
            model_name='rawmaterialmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('metal_type', 'metal_purity')},
        ),
    ]
