# Generated by Django 6.0.2 on 2026-02-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('settings_app', '0002_bankaccount_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchases', to='settings_app.bankaccount', verbose_name='Compte bancaire'),
        ),
    ]
