# Generated by Django 6.0.2 on 2026-02-28 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_printqueue'),
        ('settings_app', '0005_merge_20260212_2012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='printqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='label_type',
            field=models.CharField(choices=[('product', 'Étiquette produit'), ('price', 'Étiquette prix'), ('test', 'Test')], default='product', max_length=20, verbose_name="Type d'étiquette"),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Imprimé le'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('printing', 'En cours'), ('printed', 'Imprimé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='printqueue',
            name='zpl_data',
            field=models.TextField(help_text="Commandes ZPL brutes à envoyer à l'imprimante", verbose_name='Données ZPL'),
        ),
        migrations.CreateModel(
            name='RFIDInventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('expected_count', models.IntegerField(default=0, verbose_name='Attendus')),
                ('found_count', models.IntegerField(default=0, verbose_name='Trouvés')),
                ('missing_count', models.IntegerField(default=0, verbose_name='Manquants')),
                ('scanned_tags', models.JSONField(blank=True, default=list, help_text='Liste des EPCs scannés: [{epc, found_at}]', verbose_name='Tags scannés')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('found_products', models.ManyToManyField(blank=True, related_name='rfid_found_in', to='products.product', verbose_name='Produits trouvés')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.stocklocation', verbose_name='Emplacement')),
                ('missing_products', models.ManyToManyField(blank=True, related_name='rfid_missing_in', to='products.product', verbose_name='Produits manquants')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Par')),
            ],
            options={
                'verbose_name': 'Session inventaire RFID',
                'verbose_name_plural': 'Sessions inventaire RFID',
                'ordering': ['-started_at'],
            },
        ),
    ]
